version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: packages/Dockerfile
    ports:
      - "3001:3001"
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/sync_engine
    depends_on:
      - db
    volumes:
      - ./packages:/app/packages

  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=sync_engine
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
